// <auto-generated />
using MeFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeFit.Migrations
{
    [DbContext(typeof(MeFitDdContext))]
    [Migration("20231120094230_MeFitEF")]
    partial class MeFitEF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeFit.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jumping jacks are a simple and effective cardiovascular exercise...",
                            Difficulty = 1,
                            Equipment = "Jump Rope",
                            Image = "https://unsplash.com/photos/a-woman-squatting-on-a-barbell-in-a-gym-iqr5wW_xwLY",
                            MuscleGroup = "Legs, Arms, Cardio",
                            Name = "Jumping Jacks"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bicycle crunches are a great abdominal exercise that targets multiple muscle groups...",
                            Difficulty = 2,
                            Equipment = "Exercise Mat",
                            Image = "https://unsplash.com/photos/woman-exercising-indoors-lrQPTQs7nQQ",
                            MuscleGroup = "Abdominals, Legs",
                            Name = "Bicycle Crunches"
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.ExerciseWorkout", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseWorkout", (string)null);

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            WorkoutId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            WorkoutId = 2
                        },
                        new
                        {
                            ExerciseId = 1,
                            WorkoutId = 2
                        },
                        new
                        {
                            ExerciseId = 2,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A beginner workout plan for getting started.",
                            Difficulty = 1,
                            Image = "https://example.com/bicyclecrunches.jpg",
                            Name = "Beginner Plan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An intermediate workout plan for advancing your fitness.",
                            Difficulty = 2,
                            Image = "https://example.com/bicyclecrunches.jpg",
                            Name = "Intermediate Plan"
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full Body Circuit",
                            Difficulty = 2,
                            Equipment = "Jump Rope",
                            Image = "https://example.com/bicyclecrunches.jpg",
                            MuscleGroup = "Legs, Arms, Core",
                            Name = "Full Body Circuit Workout",
                            Reps = 10,
                            Sets = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-Intensity Interval Training (HIIT)",
                            Difficulty = 3,
                            Equipment = "Exercise Mat",
                            Image = "https://example.com/bicyclecrunches.jpg",
                            MuscleGroup = "Cardio, Legs, Arms",
                            Name = "HIIT Workout",
                            Reps = 12,
                            Sets = 4
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutPlan");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            WorkoutId = 1
                        },
                        new
                        {
                            PlanId = 2,
                            WorkoutId = 2
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.ExerciseWorkout", b =>
                {
                    b.HasOne("MeFit.Data.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeFit.Data.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("MeFit.Data.Models.WorkoutPlan", b =>
                {
                    b.HasOne("MeFit.Data.Models.Plan", "Plan")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeFit.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("MeFit.Data.Models.Plan", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("MeFit.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
