// <auto-generated />
using System;
using MeFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeFit.Migrations
{
    [DbContext(typeof(MeFitDdContext))]
    partial class MeFitDdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeFit.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fb9515d-844b-4e6b-8860-5b6551d656e0"),
                            Description = "Jumping jacks are a simple and effective cardiovascular exercise...",
                            Difficulty = 1,
                            Equipment = "Jump Rope",
                            Image = "https://unsplash.com/photos/a-woman-squatting-on-a-barbell-in-a-gym-iqr5wW_xwLY",
                            MuscleGroup = "Legs, Arms, Cardio",
                            Name = "Jumping Jacks"
                        },
                        new
                        {
                            Id = new Guid("9fa664eb-b5d5-46e1-9c0c-fb42d0861d17"),
                            Description = "Bicycle crunches are a great abdominal exercise that targets multiple muscle groups...",
                            Difficulty = 2,
                            Equipment = "Exercise Mat",
                            Image = "https://unsplash.com/photos/woman-exercising-indoors-lrQPTQs7nQQ",
                            MuscleGroup = "Abdominals, Legs",
                            Name = "Bicycle Crunches"
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.ExerciseWorkout", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseWorkouts");

                    b.HasData(
                        new
                        {
                            ExerciseId = new Guid("8fb9515d-844b-4e6b-8860-5b6551d656e0"),
                            WorkoutId = new Guid("66f51fe4-3e3c-4cdb-a136-a6f21dac25d5")
                        },
                        new
                        {
                            ExerciseId = new Guid("9fa664eb-b5d5-46e1-9c0c-fb42d0861d17"),
                            WorkoutId = new Guid("5f83d4ae-ddd0-4d34-a2dd-cd27928bde9b")
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e6622a0-b931-45b7-a102-971c734b0030"),
                            Description = "A beginner workout plan for getting started.",
                            Difficulty = 1,
                            Image = "https://example.com/bicyclecrunches.jpg",
                            Name = "Beginner Plan"
                        },
                        new
                        {
                            Id = new Guid("d15cd9c5-cf68-402e-8a02-38ab898395b6"),
                            Description = "An intermediate workout plan for advancing your fitness.",
                            Difficulty = 2,
                            Image = "https://example.com/bicyclecrunches.jpg",
                            Name = "Intermediate Plan"
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66f51fe4-3e3c-4cdb-a136-a6f21dac25d5"),
                            Description = "Full Body Circuit",
                            Difficulty = 2,
                            Equipment = "Jump Rope",
                            Image = "https://example.com/bicyclecrunches.jpg",
                            MuscleGroup = "Legs, Arms, Core",
                            Name = "Full Body Circuit Workout",
                            Reps = 10,
                            Sets = 3
                        },
                        new
                        {
                            Id = new Guid("5f83d4ae-ddd0-4d34-a2dd-cd27928bde9b"),
                            Description = "High-Intensity Interval Training (HIIT)",
                            Difficulty = 3,
                            Equipment = "Exercise Mat",
                            Image = "https://example.com/bicyclecrunches.jpg",
                            MuscleGroup = "Cardio, Legs, Arms",
                            Name = "HIIT Workout",
                            Reps = 12,
                            Sets = 4
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.WorkoutPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlanId", "WorkoutId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutPlan");

                    b.HasData(
                        new
                        {
                            PlanId = new Guid("9e6622a0-b931-45b7-a102-971c734b0030"),
                            WorkoutId = new Guid("66f51fe4-3e3c-4cdb-a136-a6f21dac25d5")
                        },
                        new
                        {
                            PlanId = new Guid("d15cd9c5-cf68-402e-8a02-38ab898395b6"),
                            WorkoutId = new Guid("5f83d4ae-ddd0-4d34-a2dd-cd27928bde9b")
                        });
                });

            modelBuilder.Entity("MeFit.Data.Models.ExerciseWorkout", b =>
                {
                    b.HasOne("MeFit.Data.Models.Exercise", "Exercise")
                        .WithMany("ExerciseWorkouts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeFit.Data.Models.Workout", "Workout")
                        .WithMany("ExerciseWorkouts")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("MeFit.Data.Models.WorkoutPlan", b =>
                {
                    b.HasOne("MeFit.Data.Models.Plan", "Plan")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeFit.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("MeFit.Data.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseWorkouts");
                });

            modelBuilder.Entity("MeFit.Data.Models.Plan", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("MeFit.Data.Models.Workout", b =>
                {
                    b.Navigation("ExerciseWorkouts");

                    b.Navigation("WorkoutPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
